name: signalr_core
description: ASP.NET Core SignalR Client written for Dart that is platform-independent, and can be used on both the command-line and the browser.
version: 1.0.8
homepage: https://github.com/jamiewest/signalr_core

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  http: ^0.13.0
  logging: ^0.11.4
  meta: ^1.1.8
  tuple: ^2.0.0-nullsafety.0
  web_socket_channel: ^1.1.0
  sse_client: 
    git:
      url: https://github.com/waseemdev/sse_client.git
  equatable: ^1.2.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.2.0
